### ISSUE TITLE
Prevent editor appearing on Instructure help and community site

### ISSUE THREAD

**Issue by voneschenbach** [shawnr/gesso#3]
The URL parameters should be updated to exclude the help and community sites at:

https://help.instructure.com

I don't anticipate a need for the editor when replying to discussion threads or submitting tickets; in fact the editor could be seen as an annoyance for system administrators.

**Comment by shawnr** [comment]
Great! Please submit any other URL patterns or specific URLs we should prohibit from the instructure.com universe.

**Comment by shawnr** [comment]
Fixed!

**Comment by voneschenbach** [comment]
Validated - thanks!
