### ISSUE TITLE
Editor appears within system admin settings for announcements

### ISSUE THREAD

**Issue by voneschenbach** [shawnr/gesso#5]
Gesso is appearing alongside the default editor in announcements, available within account settings. You can see this if you go to your prep space account and click settings, announcements. I am wondering if there is a way to restrict the editor to function only where the Rich Text Editor appears within course objects?

**Comment by voneschenbach** [comment]
http://screencast.com/t/zLgZdP6vox

**Comment by shawnr** [comment]
@voneschenbach Should we take a liberal approach to applying the replacement editor (meaning, try to replace all textareas and only exclude the obviously super bad situations)? Or should we take a more restrictive approach (meaning, we only replace the editor on pages we know are good for that)?

Do you have an opinion about that?

**Comment by voneschenbach** [comment]
It might make sense for us to sit down and go through Canvas to see which approach would be easier to implement and sustain. I am not sure if it is easy to identify specific areas where the Rich Text Editor is used, and if it makes sense to adjust the URL pattern to those places. If it's 5 places, it may make sense, but if the RTE is used in dozens of places it may not.

**Comment by shawnr** [comment]
True, true.

I'll see if I can block the most problematic stuff based on tickets, but let's get together next week and see what we can figure out for where makes sense to invoke this thing.

In the meantime, new version blocks editor on discussions and announcements.

**Comment by voneschenbach** [comment]
Oops - I should have provided the URL for which announcements. I was referring to the admin announcements at:

https://seattleu.instructure.com/accounts/85768/settings

The RTE under course announcements should allow use of the Gesso editor. Example URL:

https://seattleu.instructure.com/courses/1297419/discussion_topics/new?is_announcement=true

**Comment by shawnr** [comment]
I will look into that! Thanks for providing that URL.
